DisableFamilyShareLock: yes

DepotResponsePatchEnabled: yes
DepotResponsePatchBypassAuthFailures: yes
InstallAppForceSuccess: yes
DepotResponsePatchDepots: []
DepotDecryptionPattern: ""
Hammerlog : 2

UseWhitelist: no
AutoFilterList: yes
AppIds: []

PlayNotOwnedGames: yes

AdditionalApps: []

DlcData: {}
DenuvoGames: {}
AppTokens: {}
FakeOffline: []
FakeAppIds: {}

IdleStatus:
  AppId: 0
  Title: ""

GameTitles: {}
SubscriptionTimestamps: {}

SafeMode: yes
Notifications: no
WarnHashMissmatch: no
NotifyInit: yes
API: no

FakeEmail: ""
FakeWalletBalance: 0

ExtendedLogging: yes

ManifestHookEnabled: yes
ManifestPattern: "E8 ? ? ? ? 05 ? ? ? ? 55 89 E5 57 56 53 81 EC 10 01 00"
GetManifestRequestCodeOffset: 0
ManifestLocalCacheFallback: yes
ManifestServerUrl: "https://manifest.activateme.workers.dev"
ManifestDepotAllowFromKeys: yes
ManifestDepots: []

ManifestHttpWorkerThreads: 4

OwnershipTicketDiskFallback: no

UserOwnsDepotHookEnabled: yes
UserOwnsDepotOffset: 0x181c610
UserOwnsDepotPattern: ""

SteamlessAutoPatchEnabled: yes
SteamlessCliPath: ""
SteamlessCliTimeoutSeconds: 120
SteamlessRecursiveScan: yes
SteamlessQuiet: yes
SteamlessAppIds: []

DepotDecryptionKeys: {}

StatSteamIds: {}

NetPacketHooksEnabled: no
NetPacketLogOnly: no
NetPacketAllowHeuristicRecv: no
BBuildAndAsyncSendFrameOffset: 0
RecvPktOffset: 0

AllowMissingPatterns: yes
PatternOverrides:
  "IClientUGC::RunIPCFrame": "e8 ?? ?? ?? ?? 8b 85 ?? ?? ?? ?? 83 c4 10 3d 67 0c d2 71"
  "IClientUserStats::RunIPCFrame": "e8 ?? ?? ?? ?? 8b 85 ?? ?? ?? ?? 83 c4 10 3d 89 65 6d 87"
  "CAPIJob::GetPlayerStats": "e8 ?? ?? ?? ?? 83 c4 10 89 c5 e9 ?? ?? ?? ?? ?? ?? 80 be ?? ?? ?? ?? 00"
  "BBuildAndAsyncSendFrame": "55 89 e5 57 e8 ?? ?? ?? ?? 81 c7 ?? ?? ?? ?? 56 53 81 ec ac 00 00 00 8b"
  "RecvPkt": "55 89 e5 57 56 e8 ?? ?? ?? ?? 81 c6 ?? ?? ?? ?? 53 83 ec 1c 8b 86 ?? ??"
